### ISSUE TITLE
Notification on written text

### ISSUE THREAD

**Issue by TildeEthDoUsPart** [RazerMoon/userNotifs#6]
Hey! Great work on your plugin, by the way.
I was wondering, do you believe it would be doable to set up an option to make notifications pop up when anyone mentions specific texts and strings of characters? Would make moderation jobs so much easier.

**Comment by RazerMoon** [comment]
Sure, I'm just using `FluxDispatcher.subscribe('MESSAGE_CREATE', ...)` to listen for all messages and then check what user created it. There shouldn't be anything stopping you from filtering the results based on anything you want.

However, I believe that kind of task should probably just be given to a bot on the server.

I also wouldn't add it to this plugin since I don't think it fits its purpose, it's called "User Notify" after all.
